config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :charges, only: [:new, :create]
  root 'charges#new'
  post '/charges',  to: 'charges#create'

  post 'subscribe' => 'charges#subscribe'
                                                                   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
		@user = User.new


		  # Amount in cents
		  @amount = 500

		  customer = Stripe::Customer.create(
		    :email => params[:stripeEmail],
		    :source  => params[:stripeToken]
		  )

		  charge = Stripe::Charge.create(
		    :customer    => customer.id,
		    :amount      => @amount,
		    :description => 'Rails Stripe customer',
		    :currency    => 'eur'
		  )

	rescue Stripe::CardError => e
		  flash[:error] = e.message
		  redirect_to new_charge_path
	end


	def subscribe


		user = params["user"]

		gibbon = Gibbon::Request.new(api_key: ENV['MAILCHIMP_KEY'])
	  gibbon.timeout = 30
		gibbon.open_timeout = 30

		gibbon.lists(ENV['MAILCHIMP_LIST']).members.create(body:{email_address: user["email"], status: "subscribed", merge_fields:{FNAME: user["first_name"], LNAME:user["last_name"]} }) rescue false

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">


      <main role="main" class="inner cover">
        <h1 class="cover-heading">
          Merci pour le paiement de <strong>€5.00</strong>!</h1>
        <p class="lead">veuillez saisir votre nom et prénom pour finaliser la procedure d'inscription a la newsletter</p>


        <%= form_for @user, url: {action: "subscribe"} do |f| %>

          <div class="form-group">
            <%= f.label(:first_name, "Nom")%>
            <%= f.text_field :first_name, class: 'form-control',placeholder: "Saisir son nom" %>
          </div>
        	<div class="form-group">
            <%= f.label(:last_name, "Prenom")%>
            <%= f.text_field :last_name, class: 'form-control',placeholder: "Saisir son prenom" %>
          </div>
          <div class="form-group">
             <%= f.label(:email, "Email")%>
             <%= f.email_field :email, class: 'form-control', placeholder: "Saisir son email" %>
           </div>

          <%= f.submit "Créer un nouvel utilisateur" %>
        <% end %>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
        </div>
      </footer>
    </div>

app/views/charges/new.html.erb
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">


      <main role="main" class="inner cover">
        <h1 class="cover-heading">Bonjour</h1>
        <p class="lead">Pour accéder aux news letters, veuillez régler</p>

        <%= form_tag charges_path do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            <label class="amount">
              <span>Amount: €5.00</span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="A month's subscription"
                  data-amount="500"
                  data-currency="eur"
                  data-locale="auto"></script>
        <% end %>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
        </div>
      </footer>
    </div>

app/views/charges/subscribe.html.erb
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">


      <main role="main" class="inner cover">
        <h1 class="cover-heading">
        Inscription effectuée !</h1>
        
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
        </div>
      </footer>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeMailchimp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </head>

  <body class="text-center">
    <%= yield %>
  </body>
</html>